# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-07-16T16:05:25+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from pathlib import Path


class ErrorResponse(BaseModel):
    reason: str = Field(..., example='Non-json data')


class SendMessageRequest(BaseModel):
    user_id: int = Field(..., example=123)
    message: str = Field(..., example='Hello world!')


class BroadcastMessageRequest(BaseModel):
    message_id: int = Field(..., example=0)
    message_text: str = Field(..., example='Hello world!')


class BroadcastMessageResponse(BaseModel):
    message_id: int = Field(..., example=0)


class MessageSentResponse(BaseModel):
    message: str = Field(..., example='Hello world!')
    message_id: int = Field(..., example=1)


class BroadcastVoteResponse(BaseModel):
    vote_id: int = Field(..., example=0)


class BroadcastQuestionRequest(BaseModel):
    question_id: int = Field(..., example=0)
    question_text: str = Field(..., example='string')


class BroadcastQuestionResponse(BaseModel):
    question_id: int = Field(..., example=0)


class Option(BaseModel):
    option_id: int = Field(..., example=0)
    option_text: str = Field(..., example='First option')


class BroadcastRegistrationRequest(BaseModel):
    registration_id: int = Field(..., example=0)
    registration_text: str = Field(..., example='string')
    options: List[Option] = Field(
        ..., example=[{'option_id': 0, 'option_text': 'string'}]
    )


class UpdateRegistrationRequest(BaseModel):
    registration_id: int = Field(..., example=0)
    registration_text: str = Field(..., example='string')
    options: List[Option] = Field(
        ..., example=[{'option_id': 0, 'option_text': 'string'}]
    )


class BroadcastRegistrationResponse(BaseModel):
    registration_id: int = Field(..., example=0)


class UpdateRegistrationResponse(BaseModel):
    registration_id: int = Field(..., example=0)


class UserIdResponse(BaseModel):
    user_id: int = Field(..., example=13)


class UserIdRequest(BaseModel):
    __root__: int = Field(..., example=90284375)


class UserValidateRequest(BaseModel):
    __root__: str = Field(
        ...,
        example='query_id=AAGcqlFKAAAAAJyqUUp6-Y62&user=%7B%22id%22%3A1246866076%2C%22first_name%22%3A%22Dante%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22S_User%22%2C%22language_code%22%3A%22en%22%7D&auth_date=1651689536&hash=de7f6b26aadbd667a36d76d91969ecf6ffec70ffaa40b3e98d20555e2406bfbb',
    )


class UserValidateResponse(BaseModel):
    valid: bool = Field(..., example=True)
    chat_id: int = Field(..., example=12387128)


class LogsResponse(BaseModel):
    logs: List[str] = Field(..., example=['log-2023-07-16', 'log-2023-07-14'])


class BroadcastVoteRequest(BaseModel):
    vote_id: int = Field(..., example=0)
    vote_text: str = Field(..., example='Which option?')
    options: List[Option] = Field(
        ..., example=[{'option_id': 0, 'option_text': 'string'}]
    )
