# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-06-28T19:01:01+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class ErrorResponse(BaseModel):
    reason: str = Field(..., example='Non-json data')


class SendMessageRequest(BaseModel):
    user_id: int = Field(..., example=123)
    message: str = Field(..., example='Hello world!')


class BroadcastMessageRequest(BaseModel):
    message_id: int = Field(..., example=0)
    message_text: str = Field(..., example='Hello world!')


class BroadcastMessageResponse(BaseModel):
    message_id: int = Field(..., example=0)


class MessageSentResponse(BaseModel):
    message: str = Field(..., example='Hello world!')
    message_id: int = Field(..., example=1)


class BroadcastVoteResponse(BaseModel):
    vote_id: int = Field(..., example=0)


class BroadcastQuestionRequest(BaseModel):
    question_id: int = Field(..., example=0)
    question_text: str = Field(..., example='string')


class BroadcastQuestionResponse(BaseModel):
    question_id: int = Field(..., example=0)


class Option(BaseModel):
    option_id: int = Field(..., example=0)
    option_text: str = Field(..., example='First option')


class BroadcastRegistrationRequest(BaseModel):
    registration_id: int = Field(..., example=0)
    registration_text: str = Field(..., example='string')
    options: List[Option] = Field(
        ..., example=[{'option_id': 0, 'option_text': 'string'}]
    )


class UpdateRegistrationRequest(BaseModel):
    registration_id: int = Field(..., example=0)
    registration_text: str = Field(..., example='string')
    options: List[Option] = Field(
        ..., example=[{'option_id': 0, 'option_text': 'string'}]
    )


class BroadcastRegistrationResponse(BaseModel):
    registration_id: int = Field(..., example=0)


class UpdateRegistrationResponse(BaseModel):
    registration_id: int = Field(..., example=0)


class BroadcastVoteRequest(BaseModel):
    vote_id: int = Field(..., example=0)
    vote_text: str = Field(..., example='Which option?')
    options: List[Option] = Field(
        ..., example=[{'option_id': 0, 'option_text': 'string'}]
    )
